export const example = [
  '/**',
  ' * A basic example of a random map script.',
  ' */',
  '',
  '<PLAYER_SETUP>',
  '',
  'random_placement',
  '',
  'start_random',
  '	percent_chance 50',
  '    #define gonna-place-tc',
  'end_random',
  '',
  '<LAND_GENERATION>',
  '',
  'base_terrain DESERT /* Cover the map with sand. */',
  '',
  '<TERRAIN_GENERATION>',
  '',
  '/* Mixing different kinds of water helps to create a more realistic look. */',
  'create_terrain MED_WATER {',
  '  base_terrain WATER',
  '  number_of_clumps 10',
  '  spacing_to_other_terrain_types 2',
  '  land_percent 40',
  '}',
  '',
  '<OBJECTS_GENERATION>',
  '',
  'create_object TOWN_CENTER {',
  '  set_place_for_every_player',
  '  min_distance_to_players 0',
  '}',
  ''
].join('\n')
